"""
Rewrited Markdown filter from set of "markup" template filters for Django.

Markdown filter requires python-markdown2 library from
http://code.google.com/p/python-markdown2/

In each case, if the required library is not installed, the filter will
silently fail and return the un-marked-up text.
"""

from django import template
from django.conf import settings
from django.utils.encoding import force_unicode
from django.utils.safestring import mark_safe

register = template.Library()

def markdown(value, arg=''):
    """
    Runs Markdown over a given value, optionally using various
    extensions python-markdown supports.

    Syntax::

        {{ value|markdown:"extension1_name,extension2_name..." }}

    To enable safe mode, which strips raw HTML and only returns HTML
    generated by actual Markdown syntax, pass "safe" as the first
    extension in the list.
    """
    try:
        import markdown2
    except ImportError:
        if settings.DEBUG:
            print("Error in {% markdown %} filter: The Python markdown2 library isn't installed.")
        return u'<pre>%s</pre>' % force_unicode(value)
    else:
        extensions = [e for e in arg.split(",") if e]
        if len(extensions) > 0 and extensions[0] == "safe":
            extensions = extensions[1:]
            safe_mode = True
        else:
            safe_mode = False

        return mark_safe(markdown2.markdown(force_unicode(value),
            extras=extensions, safe_mode=safe_mode))

markdown.is_safe = True

register.filter(markdown)
